services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    volumes:
      - type: bind
        source: services/elasticsearch/dev/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: services/elasticsearch/dev/jvm.options
        target: /usr/share/elasticsearch/config/jvm.options
      - type: volume
        source: data-1-volume
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
