services:
  logstash:
    env_file:
      - ${ENV_FILE_PATH}
    ports:
      - "${LOGSTASH_PORT}:5000/tcp"
    volumes:
      - type: bind
        source: ${LOGSTASH_PATH}/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
      - type: bind
        source: ${LOGSTASH_PATH}/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
    depends_on:
      elasticsearch:
        condition: service_healthy