version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: backend
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  backend:
    build: .
    container_name: spring_boot_app
    environment:
      datasource.username: user
      datasource.password: 1234
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql-data:
    driver: local

networks:
  backend:
    driver: bridge
