jwt:
  tokens:
    access:
      secret-key: ${JWT_ACCESS_TOKEN_SECRET}
      expirationSeconds: ${JWT_ACCESS_EXPIRATION:1200}
      issuer: ${JWT_ISSUER}
      audience: ${JWT_AUDIENCE}
      algorithm: ${JWT_ALGORITHM}
      cookie:
        name: ${JWT_COOKIE_NAME}
        enabled: true

    refresh:
      secret-key: ${JWT_REFRESH_TOKEN_SECRET}
      expirationSeconds: ${JWT_REFRESH_EXPIRATION:30000}
      issuer: ${JWT_ISSUER}
      audience: ${JWT_AUDIENCE}
