spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/mysql?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: 1234
    dialect: org.hibernate.dialect.MySQLDialect
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: elasticsearch:9200
      rest:
        uris: http://elasticsearch:9200
