server:
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  server:
    url: ${SERVER_URL}
  error:
    whitelabel:
      enabled: false