datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: ${MYSQL_URL}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  hikari:
    minimum-idle: 1
    maximum-pool-size: 3
    connection-timeout: 20000
    initialization-fail-timeout: 60000

jpa:
  open-in-view: true
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 100

elasticsearch:
  uris: ${ELASTICSEARCH_URL}
