springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: https://localhost/v3/api-docs
    enabled: true
    path: /swagger-ui.html
    openapi:
      servers:
        - url: https://localhost
          description: Local Server (HTTPS)

kibana:
  url: https://localhost/kibana/