spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mydb?useUnicode=true&character_set_server=utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 1234
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
