spring:
  application:
    name: portfolio

  config:
    import:
      - optional:classpath:${spring.profiles.active}/application-${spring.profiles.active}_auth.yml
      - optional:classpath:${spring.profiles.active}/application-${spring.profiles.active}_db.yml
      - optional:classpath:${spring.profiles.active}/application-${spring.profiles.active}_docs.yml
      - optional:classpath:${spring.profiles.active}/application-${spring.profiles.active}_server.yml

  profiles:
    group:
      dev: [ "dev_auth", "dev_db", "dev_server" ,"dev_docs" ]
      prod: [ "prod_auth", "prod_db", "prod_server", "prod_docs" ]
    active: dev