spring:
  datasource:
    url: jdbc:h2:./data/local
    driver-class-name: org.h2.Driver
    username: sa
    password:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: fc3ff2ab2cba9667d0afc24a3cf26c46
            client-secret: 1234
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: DEBUG
    src.global.common.controller: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
