spring:
  application:
    name: backend

  config:
    import:
      - optional:classpath:${spring.profiles.active}/application-${spring.profiles.active}_auth.yml
      - optional:classpath:${spring.profiles.active}/application-${spring.profiles.active}_data.yml
      - optional:classpath:${spring.profiles.active}/application-${spring.profiles.active}_db.yml
      - optional:classpath:${spring.profiles.active}/application-${spring.profiles.active}_docs.yml
      - optional:classpath:${spring.profiles.active}/application-${spring.profiles.active}_server.yml
  profiles:
    group:
      dev: [ "dev_auth", "dev_data", "dev_db", "dev_docs", "dev_server"]
      prod: [ "prod_auth", "prod_data", "prod_db", "prod_docs", "prod_server"]
    active: ${SPRING_PROFILES_ACTIVE}