spring:
  datasource:
    url: jdbc:h2:./data/local
    driver-class-name: org.h2.Driver
    username: sa
    password:
  profiles:
    include: secret

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: DEBUG
    src.global.common.controller: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
