spring:
  application:
    name: backend
  profiles:
    active: local
  config:
    import: "classpath:application-secret.yml"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  config: classpath:logback/logback-spring.xml