services:
  logstash:
    ports:
      - "${LOGSTASH_PORT}:${LOGSTASH_PORT}/tcp"
    volumes:
      - type: bind
        source: services/logstash/dev/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
      - type: bind
        source: services/logstash/dev/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
    depends_on:
      master-node-1:
        condition: service_healthy
      data-node-1:
        condition: service_healthy