services:
  kibana:
    ports:
      - "5601:5601"
    volumes:
      - type: bind
        source: services/kibana/dev/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    depends_on:
      elasticsearch:
        condition: service_healthy