services:
  master-node-1:
    env_file:
      - ${ENV_FILE_PATH}
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: master-node-1
    platform: linux/amd64
    networks:
      - internal

  master-node-2:
    env_file:
      - ${ENV_FILE_PATH}
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: master-node-2
    platform: linux/amd64
    networks:
      - internal

  master-node-3:
    env_file:
      - ${ENV_FILE_PATH}
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: master-node-3
    platform: linux/amd64
    networks:
      - internal

  data-node-1:
    env_file:
      - ${ENV_FILE_PATH}
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: data-node-1
    platform: linux/amd64
    networks:
      - internal

  kibana:
    env_file:
      - ${ENV_FILE_PATH}
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    networks:
      - external

  logstash:
    env_file:
      - ${ENV_FILE_PATH}
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    networks:
      - external

  mysql:
    env_file:
      - ${ENV_FILE_PATH}
    image: mysql:8.0
    container_name: mysql
    networks:
      - external

volumes:
  data-1-volume:
  data-2-volume:
  mysql-volume:


networks:
  internal:
    driver: bridge
  external:
    driver: bridge
