services:

  mysql:
    env_file:
      - ${ENV_FILE_PATH}
    networks:
      - external

  redis:
    env_file:
      - ${ENV_FILE_PATH}
    networks:
      - external

  elasticsearch:
    platform: linux/amd64
    env_file:
      - ${ENV_FILE_PATH}
    networks:
      - external

  logstash:
    env_file:
      - ${ENV_FILE_PATH}
    networks:
      - external

  kibana:
    env_file:
      - ${ENV_FILE_PATH}
    networks:
      - external

volumes:
  es-data:
  redis-data:
  mysql-volume:
  logstash-pipeline:

networks:
  external:
    driver: bridge
