services:
  kibana:
    env_file:
      - ${ENV_FILE_PATH}
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    networks:
      - external

  logstash:
    env_file:
      - ${ENV_FILE_PATH}
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    networks:
      - external

  mysql:
    env_file:
      - ${ENV_FILE_PATH}
    image: mysql:8.0
    container_name: mysql
    networks:
      - external

volumes:
  mysql-volume:

networks:
  external:
    driver: bridge
