services:
  mysql:
    env_file:
      - ${ENV_FILE_PATH}
    networks:
      - external

  redis:
    restart: unless-stopped
    networks:
      - external

  logstash:
    container_name: logstash
    env_file:
      - ${ENV_FILE_PATH}
    networks:
      - external

  kibana:
    env_file:
      - ${ENV_FILE_PATH}
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    networks:
      - external

volumes:
  redis-data:
  mysql-volume:

networks:
  external:
    driver: bridge
