services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    platform: linux/amd64
    networks:
      - common-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    networks:
      - common-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    networks:
      - common-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - common-net

volumes:
  mysql-data:

networks:
  common-net:
    driver: bridge
