services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - ../.env.${ENVIRONMENT}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - common-net

volumes:
  mysql-data:
    driver: local

networks:
  common-net:
    driver: bridge

