services:
  backend:
    container_name: spring_boot_app
    build:
      context: ../
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart: always
    environment:
      MYSQL_URL: jdbc:mysql://mysql:3306/backend?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    depends_on:
      - mysql
    networks:
      - common-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234      # 루트 비밀번호 설정
      MYSQL_USER: user               # 사용자 설정
      MYSQL_PASSWORD: 1234           # 사용자 비밀번호 설정
      MYSQL_DATABASE: backend        # 데이터베이스 설정
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf   # MySQL 설정 파일
      - mysql-data:/var/lib/mysql    # 데이터 저장
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 초기화 SQL 스크립트
    networks:
      - common-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf:/etc/nginx/conf.d:ro
      - ../nginx/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ../nginx/certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - backend
    networks:
      - common-net

volumes:
  mysql-data:
    driver: local

networks:
  common-net:
    external: true
