services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    ports:
      - "${LOGSTASH_PORT}:${LOGSTASH_PORT}/tcp"
    volumes:
      - type: bind
        source: services/logstash/dev/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
      - type: bind
        source: services/logstash/dev/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
    depends_on:
      elasticsearch:
        condition: service_healthy