# 클러스터 설정
cluster:
  name: cluster
  # 최초 실행 시 명시된 노드들을 대상으로 마스터 노드를 선출
  initial_master_nodes: ["master-node-1", "master-node-2", "master-node-3"]

# 노드 설정
node:
  name: master-node-1
  roles: [master]

# 사용중인 힙메모리 영역을 다른 자바 프로그램이 간섭 못하도록 미리 점유하는 설정
bootstrap:
  memory_lock: true

# 클러스터 구성을 위한 바인딩 할 원격 노드의 IP 또는 도메인 주소
discovery:
  seed_hosts: ["master-node-1", "master-node-2", "master-node-3"]


# 실행되는 서버의 ip 주소
network:
  host: 0.0.0.0

# 클라이언트와 통신하기 위한 http 포트 설정
http:
  port: 9200

# Elasticsearch 노드들 끼리 서로 통신하기 위한 tcp 포트를 설정
transport:
  port: 9300