spring:
  datasource:
    url: jdbc:mysql://prod-db-host/db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 1234
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
