services:
  master-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: master-node-1
    platform: linux/amd64
    volumes:
      - type: bind
        source: services/elasticsearch/prod/master-1/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: services/elasticsearch/prod/master-1/jvm.options
        target: /usr/share/elasticsearch/config/jvm.options
    ports:
      - "9300:9300"
    healthcheck:
      test: curl -s http://master-node-1:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  master-node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: master-node-2
    platform: linux/amd64
    volumes:
      - type: bind
        source: services/elasticsearch/prod/master-2/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: services/elasticsearch/prod/master-2/jvm.options
        target: /usr/share/elasticsearch/config/jvm.options
    ports:
      - "9301:9300"
    healthcheck:
      test: curl -s http://master-node-2:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  master-node-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: master-node-3
    platform: linux/amd64
    volumes:
      - type: bind
        source: services/elasticsearch/prod/master-3/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: services/elasticsearch/prod/master-3/jvm.options
        target: /usr/share/elasticsearch/config/jvm.options
    ports:
      - "9302:9300"
    healthcheck:
      test: curl -s http://master-node-3:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  data-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: data-node-1
    platform: linux/amd64
    volumes:
      - type: bind
        source: services/elasticsearch/prod/data-1/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: data-1-volume
        target: /usr/share/elasticsearch/data
      - type: bind
        source: services/elasticsearch/prod/data-1/jvm.options
        target: /usr/share/elasticsearch/config/jvm.options
    ports:
      - "9200:9200"
      - "9303:9300"
    healthcheck:
      test: curl -s http://data-node-1:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

volumes:
  data-1-volume:
  data-2-volume:

networks:
  internal:
    driver: bridge