services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    platform: linux/amd64
    volumes:
      - ./elasticsearch.yml:/elk/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9200:9200"
    networks:
      - common-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    volumes:
      - ./kibana.yml:/elk/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - common-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline/logstash.conf:/elk/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "5001:5000/tcp"
      - "5001:5000/udp"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - common-net

networks:
  common-net:
    external: true
    name: common-net